name: Matrix Demo
on: push
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [12, 14, 20]
        operation-system: [ubuntu-latest, windows-latest]
    runs-on: ${{matrix.operation-system}}
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install ModeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
      - name: Install dependencies
        run: npm ci
      - name: Build code
        run: npm run build
